### ISSUE TITLE
[feat] Add Monerium EURe support

### ISSUE THREAD

**Issue by julienbrg** [w3hc/gcfa#24]
On GnosisChain Network

**Comment by JamesFerggy1995** [comment]
get inspired https://github.com/w3hc/gcfa/pull/22/files

**Comment by skinito** [comment]
contract EURe in gnosis chain
https://github.com/monerium/smart-contracts#gnosischain
https://gnosisscan.io/token/0xcB444e90D8198415266c6a2724b7900fb12FC56E
