### ISSUE TITLE
[feat] Add min and max amounts per transaction

### ISSUE THREAD

**Issue by julienbrg** [w3hc/gcfa#3]
**blocked** by https://github.com/w3hc/gcfa/issues/35
To secure mul and div.

**Comment by bertux** [comment]
https://solidity-fr.readthedocs.io/fr/latest/080-breaking-changes.html?highlight=safemath#how-to-update-your-code confirms the * used for multiplication is safe since version 0.8.0 of Solidity.

**Comment by bertux** [comment]
https://solidity-fr.readthedocs.io/fr/latest/types.html#entiers explains the different types of integers numbers in Solidity so reducing the number of bytes used for the amounts would reduce the risks created by big amounts.

**Comment by bertux** [comment]
blocked by #35
