### ISSUE TITLE
gCFA has no decimals

### ISSUE THREAD

**Issue by bertux** [w3hc/gcfa#35]

**Comment by bertux** [comment]
Simplify the decimals function at https://github.com/w3hc/gcfa/blob/9d9185ce87a9647520d55da93dfa6d996f416548/contracts/ERC20Wrapper.sol#L38 to always return 0 so only line https://github.com/w3hc/gcfa/blob/9d9185ce87a9647520d55da93dfa6d996f416548/contracts/ERC20Wrapper.sol#LL44C37-L44C37 should stay in this function.

**Comment by privatyvesndoutoume** [comment]
PR reverted so issue re-opened and waiting for correct PR

**Comment by bertux** [comment]
Won't fix because we want to be fair by keeping the same number of decimals for gCFA than the € token wrapped.
