### ISSUE TITLE
[feat] Add deploy script

### ISSUE THREAD

**Issue by julienbrg** [w3hc/gcfa#7]
- Celo
- Fuse

**Comment by bertux** [comment]
done on Celo testnet but not pushed yet.

- GoodCFA: https://alfajores.celoscan.io/token/0x80fd71c9dfe2998480815bfbd053aa7770439c6b#code

- GoodEuro: https://alfajores.celoscan.io/token/0x8c55946a2d188e6011a989fabc22ab6b6fa7ed18#code

@julienbrg please push the branch to create the PR.
